### ISSUE TITLE
Emphasize more that this project is outdated

### ISSUE THREAD

**Issue by christian-konrad** [camunda-community-hub/zeebe-simple-tasklist#255]
A user tried this project and was wondering that it uses job workers instead of the REST API.

With the intro of the Zeebe REST API for task management and job worker-based tasks becoming outdated, we should highlight that users should not use this project as a starting guide.

**Comment by saig0** [comment]
@christian-konrad we should clarify a few things. 

This project doesn't use the Tasklist APIs, correct. Historically, it works differently. 

But, the fact that it doesn't use the Tasklist API doesn't mean the project is outdated. 

Indeed, it doesn't support the same features as Camunda Tasklist. Especially, the new native user tasks with Camunda 8.5 are not supported. 

In general, I recommend using Camunda Tasklist instead. However, some users might see value in this project, at least for now.

**Comment by christian-konrad** [comment]
I agree, outdated is probably not the accurate term - we just need to make sure that net new users do not consider this as a starting point. Let me change the note to a hint that this is for advanced users, and does not support the most recent user task type

**Comment by saig0** [comment]
@christian-konrad thank you for your understanding. :+1: 

I updated the README once more and marked the project as deprecated. Why? I as the maintainer don't plan to continue working actively on the project.
