### ISSUE TITLE
Update GitHub deployment Action

### ISSUE THREAD

**Issue by xomiamoore** [camunda-community-hub/zeebe-simple-tasklist#263]
Hello! We had to make a few changes to our community's Maven deployment Action. Specifically, we updated the secret names and deployment credentials.

Please update to [the latest release, v. 1.2.1](https://github.com/camunda-community-hub/community-action-maven-release/releases/tag/v1.2.1), to make sure your Action works. Thank you!

**Comment by saig0** [comment]
Done. I pinned the version to `v1`. :rocket:
