### ISSUE TITLE
Change context-path not working as expected

### ISSUE THREAD

**Issue by dekke046** [camunda-community-hub/zeebe-simple-tasklist#38]
Hi,

I am trying to have simple-takslist running on a different path then /
Therefore I have added:
`- server.servlet.context-path=/tasklist`
in the environment part of docker-compose.

It works, application is listening at /tasklist, but is giving the following layout:
![image](https://user-images.githubusercontent.com/12866158/81931427-635ac380-95ea-11ea-971a-093ba03a08e1.png)

So made more changes:

Changed the path’s in the the template files and mounted the changed template folder with docker-compose to /app/resources/templates. Changes that I made where e.g.
`<form id="login-form" action="/tasklist/login" method="post">`
in login.html

But also changes in header.html to add the right path.
that was already better, but adding a new user for example did not work, so I moved on to the .js files

changes to .js files, since creating user’s did not work anymore, so for example:
url: `withSecurityToken('/tasklist/api/tasks/' + taskKey + '/claim'), url: withSecurityToken('/tasklist/api/users/'), url: withSecurityToken('/tasklist/api/users/' + username)`, in app.js and mounted to changes js folder to /app/resources/public/js

This resulted in a working app in /tasklist but only the login process did not work.

After login it does a wrong redirect (**missing /tasklist prefix**), if after login you change the path manually in the browser to the proper URL it works.

I suspect it is due to src/main/java/io/zeebe/tasklist/view/ViewController.java:
![image](https://user-images.githubusercontent.com/12866158/81932015-4f639180-95eb-11ea-83c1-7eeb5dd9545b.png)

The RedirectView not respecting the path settings from server.servlet.context-path.

Thanks,

Maarten

**Comment by saig0** [comment]
A similar feature was implemented here: zeebe-io/zeebe-simple-monitor/pull/209
The PR could be adopted because the code base is similar.
