### ISSUE TITLE
Can Postgres be used?

### ISSUE THREAD

**Issue by danshapir** [camunda-community-hub/zeebe-simple-tasklist#86]
If I understand the architecture properly, the data exported through Hazelcast is saved in memory (the list of tasks). Meaning if the app restarts all the data is lost?

If so, can Postgres be used?

**Comment by saig0** [comment]
Yes, correct. 

The database can be configured similar to Zeebe Simple Monitor. See here: https://github.com/camunda-community-hub/zeebe-simple-monitor#change-the-database

**Comment by saig0** [comment]
I new issue is created to provide a docker image: #89
