### ISSUE TITLE
Support Zeebe's user tasks

### ISSUE THREAD

**Issue by saig0** [camunda-community-hub/zeebe-simple-tasklist#87]
Since Zeebe 1.0.0, user tasks are supported: https://docs.camunda.io/docs/reference/bpmn-processes/user-tasks/user-tasks

In order to support user tasks, the app must watch for jobs of the type `io.camunda.zeebe:userTask`.
The new job type replaces the previous job type `user`.

**Comment by danshapir** [comment]
Is there any ETA for this feature?

**Comment by saig0** [comment]
I plan to work on it at the end of Jun or the beginning of July. 
I've some other projects which need some love before :smile: 

But I'm happy if someone wants to contribute here :wink:

**Comment by dongxin980422** [comment]
When will a new version be released

**Comment by dongxin980422** [comment]
The task list is empty when connected

**Comment by saig0** [comment]
Unfortunately, I didn't have time yet. I hope to work on it in December.

**Comment by tbfly** [comment]
> The task list is empty when connected

Now, I can get task list. But can't show taskform with luck!

**Comment by tbfly** [comment]
> > The task list is empty when connected
> 
> Now, I can get task list. But can't show taskform with luck!

https://github.com/camunda-community-hub/zeebe-simple-tasklist/issues/88

some update.

**Comment by saig0** [comment]
Done by #91 :rocket:
