### ISSUE TITLE
Docker image with postgres prebuilt

### ISSUE THREAD

**Issue by danshapir** [camunda-community-hub/zeebe-simple-tasklist#89]
Hey,

When you want to use this awesome project with k8s and need PostgreSQL, it's extremely hard to achieve without a prebuilt docker image that already contains the PostgreSQL driver preconfigured.

Can you please add to your release? 

Thanks,
Dan

**Comment by saig0** [comment]
Yes, I agree. The easiest way would be to add the Postgres driver directly. Can be done in the same way as https://github.com/camunda-community-hub/zeeqs/pull/163
