### ISSUE TITLE
Migrate to Zeebe 1.x 

### ISSUE THREAD

**Issue by saig0** [camunda-community-hub/zeebe-simple-tasklist#90]
Currently, the project uses a Zeebe client `0.26.x`. In order to support the new Zeebe/Camunda Cloud versions `>= 1.0`, we need to update the Zeebe client. 

Similar projects are already migrated, for example, https://github.com/camunda-community-hub/zeebe-simple-monitor/pull/250.

**Comment by tbfly** [comment]
Hello, I'm trying to dig this problem.
Now, in 1.x+, we need HazelcastService to read all jobrecord? While in 0.26 we have UserTaskJobHandler to add "taskForm" and "Variables".
Will you please, guide me where to start？
Now，I can read task/job info from ZeebeHazelcast, but I can't find a method to read  "taskForm".
Do I need to check zeebe-simple-monitor path, use ZeebeImportService to get process/instance resource, then get "taskForm" to show?
Thx!

**Comment by tbfly** [comment]
I get some clue from: https://github.com/camunda-community-hub/zeebe-simple-tasklist/blob/master/src/test/resources/custom-task-form.html

**Comment by saig0** [comment]
@tbfly awesome that you want to contribute :rocket: 

> Now, in 1.x+, we need HazelcastService to read all jobrecord?

No. We can still use the job worker to read the tasks. The `formKey` is stored as [io.camunda.zeebe:formKey](https://github.com/camunda-cloud/zeebe/blob/develop/protocol/src/main/java/io/camunda/zeebe/protocol/Protocol.java#L68-L69) in the task headers.

But it order to read the form, we need to import the process record. The form is stored in the process extension [zeebe:userTaskForm](https://docs.camunda.io/docs/reference/bpmn-processes/user-tasks/user-tasks/#user-task-forms).

**Comment by tbfly** [comment]
> @tbfly awesome that you want to contribute 🚀
> 
> > Now, in 1.x+, we need HazelcastService to read all jobrecord?
> 
> No. We can still use the job worker to read the tasks. The `formKey` is stored as [io.camunda.zeebe:formKey](https://github.com/camunda-cloud/zeebe/blob/develop/protocol/src/main/java/io/camunda/zeebe/protocol/Protocol.java#L68-L69) in the task headers.
Thx, I will check this path. Now, I just use HazelcastService  to load the exist taskinfo in jobrecord. 

> But it order to read the form, we need to import the process record. The form is stored in the process extension [zeebe:userTaskForm](https://docs.camunda.io/docs/reference/bpmn-processes/user-tasks/user-tasks/#user-task-forms).

Exactly! I found this way too. "UserTaskJobHandler" still useful for import userService job, "taskForm" and "formFields" info.

**Comment by tbfly** [comment]
> > @tbfly awesome that you want to contribute 🚀
> > > Now, in 1.x+, we need HazelcastService to read all jobrecord?
> > 
> > 
> > No. We can still use the job worker to read the tasks. The `formKey` is stored as [io.camunda.zeebe:formKey](https://github.com/camunda-cloud/zeebe/blob/develop/protocol/src/main/java/io/camunda/zeebe/protocol/Protocol.java#L68-L69) in the task headers.
> 
> @saig0 Thx, I will check this path. Now, I just use HazelcastService to load the exist taskinfo in jobrecord. By now, #87 this issue: 87 is sloved.
> 
> > But it order to read the form, we need to import the process record. The form is stored in the process extension [zeebe:userTaskForm](https://docs.camunda.io/docs/reference/bpmn-processes/user-tasks/user-tasks/#user-task-forms).
> 
> Exactly! I found this way too. "UserTaskJobHandler" still useful for import userService job, "taskForm" and "formFields" info.
> 
> I just found the Demo.java code useful to test for load taskForm and formFields. [#90 (comment)](https://github.com/camunda-community-hub/zeebe-simple-tasklist/issues/90#issuecomment-978882332)

https://github.com/camunda-community-hub/zeebe-simple-tasklist/issues/88

Some update by  using [io.camunda.zeebe:formKey].

**Comment by saig0** [comment]
Done by #91 :rocket:
